### ISSUE TITLE
Als beheerder wil ik weten hoe een evt. aanwezige roadmap van een standaard er uitziet zodat ik daar bij mijn planning rekening mee kan houden.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-beheer#47]
...zodat ik daar bij mijn onderhoudsplanning rekening mee kan houden.

**Definition of ready**

- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg voor een sprint
- [ ] Product Owner akkoord en voorzien van prio
- [ ] Voorzien van Acceptatiecriteria
- [ ] Voorzien van Definition of Done
- [ ] Voorzien van taken
- [ ] Vastgelegd Github en in geplaatst in kolom ready for sprint

**Definition of done**

**Algemeen**

Een werkwijze/middel/tools om ZDS-API goed in beheer te nemen.

**Specifiek**
 
- [ ] We moeten bepalen of het aanvaardbaar is dat een ontwikkelproject de planning van de beheerders kan afdwingen middels beloftes dan wel roadmap die zijn gedaan dan wel afgegeven tijdens het ontwikkeltraject. 
- [ ] Indien dat het geval  is moet een eventuele roadmap en/of belofte overgedragen worden
- [ ] ...

**Oplossingsrichting**

...

**Acceptatiecriteria**

- [ ] Niet belemmerend werken voor beheer andere standaarden
- [ ] Er is een duidelijke richtlijn hoe hiermee moet worden omgegaan.
- [ ] ...

**Taken**

- [ ] ... (@...)
- [ ] ... (@...)

**Comment by TCIMEddy** [comment]
@melsk-r te algemeen en wordt afgedekt door overdracht baaklog?!

**Comment by melsk-r** [comment]
@TCIMEddy Klopt dat, is de backlog gelijk aan de roadmap, Ik heb het gevoel dat de roadmap richting geeft bij het bepalen van de prio's van de userstories in de backlog.
Bijv. In de roadmap kan worden opgenomen dat archivering door de stakeholders wordt gezien als een van de belangrijkste nog te ontwikkelen deliverables. Dan weet ik als PO dat ik de userstories in de backlog die daarmee verband houden de prio H moet geven.

**Comment by TCIMEddy** [comment]
@melsk-r Klopt! En het bundelen van gelijksoortige user stories (lees toebehorend aan EPIC) kan efficiency in sprint verhogen
